name: Build and Release

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19.2'

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o aish-linux main.go
        GOOS=darwin GOARCH=amd64 go build -o aish-darwin-amd64 main.go
        GOOS=darwin GOARCH=arm64 go build -o aish-darwin-arm64 main.go


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.OMNI_RELEASE_TOKEN }}
      with:
        tag_name: v0.0.1-alpha.2
        release_name: Release v0.0.1-alpha.2
        body: |
          Changes in this release:
          - Added new feature
        draft: false
        prerelease: false


    - name: Upload Release Asset for Linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.OMNI_RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./aish-linux
        asset_name: aish-linux
        asset_content_type: application/octet-stream

    - name: Upload Release Asset for Mac amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.OMNI_RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./aish-amd64
        asset_name: aish-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset for Mac arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.OMNI_RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./aish-arm64
        asset_name: aish-arm64
        asset_content_type: application/octet-stream
